apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-jacket.fullname" . }}
  labels:
    app: {{ include "model-jacket.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "model-jacket.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "model-jacket.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: model-jacket
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /models/model.pt
          resources: {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5