replicaCount: 2
image:
  repository: model-jacket
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
service:
  type: ClusterIP
  port: 80
sloLatencyMs: 200